configs:
  - path: /v2/configurations/zookeeper_service/latest
    content: >
      {
        "success": true,
        "data": {
          "zookeeper_hosts": "[{\"hostname\":\"default-opscode-ubuntu-1804-chef-14\",\"ip\":\"0.0.0.0\"}]"
        }
      }
    contentType: application/json
    statusCode: 200
  - path: /ping
    content: pong
    contentType: application/json
    statusCode: 200
