---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: default
    run_list:
      - recipe[zookeeper]
      - recipe[kafka::kafka]
    driver_config:
      customize:
        memory: 2048
      network:
        - ['private_network', {ip: '192.168.33.50'}]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      zookeeper:
        role: zookeeper-cluster
        hosts: ['default-opscode-ubuntu-1804-chef-14']
        my_id: 1
        package_retries: 1
        jvm_opts:
          -Xmx128m:
      kafka:
        zookeeper:
          role: zookeeper-cluster
          hosts: ['default-opscode-ubuntu-1804-chef-14']
        kafka:
          role: kafka-cluster
          hosts: ['default-opscode-ubuntu-1804-chef-14']
          auto_restart: true
          cli_opts:
            -Xmx4g: nil
            -Xms4g: nil
            -Xmx384m: ''
            -Xms64m: ''
        burrow:
          zookeeper_clusters: ['localhost']
          kafka_cluster: 
            broker_ips: ['localhost']
            name: 'guja'
            zookeeper_ips: ['localhost']
          topic_refresh_interval: 60
          offset_refresh_interval: 30

        package_retries: 1
