---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  # Install a stand-alone zookeeper
  - name: zookeeper
    run_list:
      - recipe[zookeeper-cookbook]
    attributes:
      zookeeper-cookbook:
        role: zookeeper-cluster
        hosts: ['zookeeper-ubuntu-1604.vagrantup.com']
        package_retries: 1
        jvm_opts:
          -Xmx128m:
  - name: default
    run_list:
      - recipe[kafka-cookbook::kafka]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      kafka-cookbook:
        zookeeper:
          role: zookeeper-cluster
          hosts: ['zookeeper-ubuntu-1604.vagrantup.com']
        kafka:
          role: kafka-cluster
          hosts: ['default-ubuntu-1604.vagrantup.com']
          auto_restart: true
          cli_opts:
            -Xmx4g: nil
            -Xms4g: nil
            -Xmx384m: ''
            -Xms64m: ''
        package_retries: 1
