---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opscode-ubuntu-18.04-chef-14
    driver:
      box: bento/ubuntu-18.04
    provisioner:
      product_name: chef
      product_version: latest

suites:
  - name: default
    run_list:
      - recipe[zookeeper]
      - recipe[kafka::kafka]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
      zookeeper:
        role: zookeeper-cluster
        hosts: ['default-ubuntu-1604.vagrantup.com']
        package_retries: 1
        jvm_opts:
          -Xmx128m:
      kafka:
        zookeeper:
          role: zookeeper-cluster
          hosts: ['default-ubuntu-1604.vagrantup.com']
        kafka:
          role: kafka-cluster
          hosts: ['default-ubuntu-1604.vagrantup.com']
          auto_restart: true
          cli_opts:
            -Xmx4g: nil
            -Xms4g: nil
            -Xmx384m: ''
            -Xms64m: ''
        package_retries: 1
