---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.7

platforms:
  - name: windows-2012r2
    driver:
      box: dhoer/windows-2012r2

suites:
  - name: nssm_test
    run_list:
      - nssm_test::install_service
    attributes:


  - name: nssm_test_modification
    run_list:
      - nssm_test::modify_service
    attributes:
