language: ruby
cache: bundler
rvm:
- 2.3.1
deploy:
  skip_cleanup: true
  edge:
    source: criteo-forks/dpl
    branch: chef_ruby2
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Applications
  client_key: .travis/client.pem
  on:
    tags: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_903558f75a9a_key -iv $encrypted_903558f75a9a_iv -in .travis/client.pem.enc -out .travis/client.pem -d
